<?php
    $banword = array(
        0 => "bite",
        1 => "couille",
        2 => "vagin",
        3 => "chatte",
        4 => "cul",
        5 => "merde",
        6 => "pisse",
        7 => "sperme",
        8 => "pute",
        9 => "putain",
        10 => " pd ",
        11 => "pédé",
        12 => "kesch",
        13 => "nazi",
        14 => "hitler",
        15 => "suicid",
        16 => "porn",
        17 => "sex",
        18 => "sperm",
        19 => "<",
        20 => ">",
        21 => "hitler"
    );